import { MigrationInterface, QueryRunner } from "typeorm";

export class initTable1675941403593 implements MigrationInterface {
    name = 'initTable1675941403593'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "province" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, CONSTRAINT "PK_4f461cb46f57e806516b7073659" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "district" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "province_id" uuid NOT NULL, CONSTRAINT "PK_ee5cb6fd5223164bb87ea693f1e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sub_district" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "district_id" uuid NOT NULL, CONSTRAINT "PK_3feea0f1a7cdea813373a32e653" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "village" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "sub_district_id" uuid NOT NULL, CONSTRAINT "PK_3ada8696ae059b2fcf82d5ab579" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(50) NOT NULL, "description" character varying(100) NOT NULL, "privilege" boolean NOT NULL DEFAULT false, "list_menu" character varying array, "created_id" uuid, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_id" uuid, "updated_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_15d4732e7824b2e67909545876f" UNIQUE ("code"), CONSTRAINT "PK_c22adcb15e7de70e1a74b4a3542" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying(100) NOT NULL, "user_name" character varying(100) NOT NULL, "avatar" character varying(255), "email" character varying(100), "address" character varying(255), "contact" text, "password" character varying NOT NULL, "salt" character varying NOT NULL, "user_category_id" uuid, "created_id" uuid, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_id" uuid, "updated_date" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_758b8ce7c18b9d347461b30228d" UNIQUE ("user_id"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "warehouse" ("created_id" uuid, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_id" uuid, "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "description" character varying(100) NOT NULL, "status_transaction" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_dcbf22551ec3827f234e532a08b" UNIQUE ("code"), CONSTRAINT "PK_965abf9f99ae8c5983ae74ebde8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "config_system" ("created_id" uuid, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_id" uuid, "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "warehouse_purchase_id" uuid NOT NULL, CONSTRAINT "PK_b1393872e92b11cb2daa5267e7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customer" ("created_id" uuid, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_id" uuid, "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "name" character varying(100) NOT NULL, "nik" character varying(100) NOT NULL, "place_birth" character varying(100) NOT NULL, "date_birth" character varying(10) NOT NULL, "street" character varying(150), "village_id" uuid, "religion" character varying(100), "martial_status" character varying(100), "job" character varying(100), "contact" character varying(100), "email" character varying(100), CONSTRAINT "UQ_68db634015cb7defd6b98f910f4" UNIQUE ("code"), CONSTRAINT "PK_a7a13f4cacb744524e44dfdad32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_category" ("created_id" uuid, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_id" uuid, "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "description" character varying(100) NOT NULL, CONSTRAINT "UQ_b8c9d50238e056e452f29ef7686" UNIQUE ("code"), CONSTRAINT "PK_0dce9bc93c2d2c399982d04bef1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_type" ("created_id" uuid, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_id" uuid, "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "description" character varying(100) NOT NULL, "product_category_id" uuid, CONSTRAINT "UQ_69a52b82458769a4d2ab1835b62" UNIQUE ("code"), CONSTRAINT "PK_e0843930fbb8854fe36ca39dae1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tp_product_code" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, CONSTRAINT "UQ_3cbd3caaf23a2d0c0abb8198b49" UNIQUE ("code"), CONSTRAINT "PK_795994215544aeba7f86cfef65a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "uom" ("created_id" uuid, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_id" uuid, "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "description" character varying(100) NOT NULL, CONSTRAINT "UQ_10abf76001c0b54960c23717f61" UNIQUE ("code"), CONSTRAINT "PK_87729daf4a43ad4efdbdef69ff9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product" ("created_id" uuid, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_id" uuid, "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "description" character varying(150) NOT NULL, "picture" character varying(255), "product_type_id" uuid, "unit_retail_id" uuid, "unit_pack_id" uuid, "unit_pack_content" numeric NOT NULL DEFAULT '0', "unit_buy_id" uuid, "unit_buy_content" numeric NOT NULL DEFAULT '0', "last_buy_price" numeric NOT NULL DEFAULT '0', "retail_sell_price" numeric NOT NULL DEFAULT '0', "retail_sell_disc" numeric NOT NULL DEFAULT '0', "pack_sell_price" numeric NOT NULL DEFAULT '0', "pack_sell_disc" numeric NOT NULL DEFAULT '0', CONSTRAINT "UQ_99c39b067cfa73c783f0fc49a61" UNIQUE ("code"), CONSTRAINT "PK_bebc9158e480b949565b4dc7a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "supplier" ("created_id" uuid, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_id" uuid, "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "description" character varying(100) NOT NULL, "address" character varying(255), "contact" character varying(100), "email" character varying(100), CONSTRAINT "UQ_e1183babf2fed1bb440905b1e53" UNIQUE ("code"), CONSTRAINT "PK_2bc0d2cab6276144d2ff98a2828" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase" ("created_id" uuid, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_id" uuid, "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supplier_id" uuid NOT NULL, "purchase_date" character varying(10), "no_invoice" character varying(30) NOT NULL, "no_invoice_ext" character varying(30), "total_price_item" numeric NOT NULL DEFAULT '0', "total_disc_item" numeric NOT NULL DEFAULT '0', "grand_price_item" numeric NOT NULL DEFAULT '0', "disc_invoice" numeric NOT NULL DEFAULT '0', "grand_price_invoice" numeric NOT NULL DEFAULT '0', "grand_price_invoice_ext" numeric NOT NULL DEFAULT '0', CONSTRAINT "PK_86cc2ebeb9e17fc9c0774b05f69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_detail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchase_head_id" uuid NOT NULL, "no_queue" integer, "product_id" uuid NOT NULL, "unit_buy_id" uuid, "unit_retail_id" uuid, "unit_buy_content" numeric NOT NULL DEFAULT '0', "buy_price_item" numeric NOT NULL DEFAULT '0', "qty_pak" numeric NOT NULL DEFAULT '0', "qty_retail" numeric NOT NULL DEFAULT '0', "qty_total" numeric NOT NULL DEFAULT '0', "total_price_item" numeric NOT NULL DEFAULT '0', "total_disc_item" numeric NOT NULL DEFAULT '0', "total_price_disc" numeric NOT NULL DEFAULT '0', CONSTRAINT "PK_b0988b2c3f2e1e5d95756b01389" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sale" ("created_id" uuid, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_id" uuid, "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "sale_date" character varying(10), "no_invoice" character varying(30) NOT NULL, "total_price_item" numeric NOT NULL DEFAULT '0', "total_disc_item" numeric NOT NULL DEFAULT '0', "grand_price_item" numeric NOT NULL DEFAULT '0', "disc_invoice" numeric NOT NULL DEFAULT '0', "grand_price_invoice" numeric NOT NULL DEFAULT '0', "grand_buy_price" numeric NOT NULL DEFAULT '0', "cash_payment" numeric NOT NULL DEFAULT '0', "non_cash_payment" numeric NOT NULL DEFAULT '0', "change" numeric NOT NULL DEFAULT '0', "rounding" numeric NOT NULL DEFAULT '0', CONSTRAINT "PK_d03891c457cbcd22974732b5de2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sale_detail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sale_head_id" uuid NOT NULL, "no_queue" integer, "product_id" uuid NOT NULL, "unit_retail_id" uuid NOT NULL, "unit_pack_id" uuid NOT NULL, "unit_pack_content" numeric NOT NULL DEFAULT '0', "price_retail" numeric NOT NULL DEFAULT '0', "price_pack" numeric NOT NULL DEFAULT '0', "sell_price_item" numeric NOT NULL DEFAULT '0', "qty_pack" numeric NOT NULL DEFAULT '0', "qty_retail" numeric NOT NULL DEFAULT '0', "qty_total" numeric NOT NULL DEFAULT '0', "total_sell_price" numeric NOT NULL DEFAULT '0', "total_sell_disc" numeric NOT NULL DEFAULT '0', "total_price_disc" numeric NOT NULL DEFAULT '0', "total_buy_price" numeric NOT NULL DEFAULT '0', CONSTRAINT "PK_4a2e151a26169857b1f3d47c198" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_card" ("created_id" uuid, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_id" uuid, "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "warehouse_id" uuid NOT NULL, "category_transaction" character varying(50) NOT NULL, "description" character varying(100) NOT NULL, "stock_start" numeric NOT NULL DEFAULT '0', "stock_add" numeric NOT NULL DEFAULT '0', "stock_out" numeric NOT NULL DEFAULT '0', "stock_end" numeric NOT NULL DEFAULT '0', CONSTRAINT "PK_4fbf097977601f59e44eb7e418f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_fifo" ("created_id" uuid, "created_date" TIMESTAMP NOT NULL DEFAULT now(), "updated_id" uuid, "updated_date" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "stock_add" numeric NOT NULL DEFAULT '0', "stock_out" numeric NOT NULL DEFAULT '0', "stock_end" numeric NOT NULL DEFAULT '0', "buy_price" numeric NOT NULL DEFAULT '0', CONSTRAINT "PK_d10b6140b4e101906e779ebabf1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "warehouse_id" uuid NOT NULL, "stock" numeric NOT NULL DEFAULT '0', CONSTRAINT "PK_092bc1fc7d860426a1dec5aa8e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "district" ADD CONSTRAINT "FK_20bbec53bfceb008df55035d900" FOREIGN KEY ("province_id") REFERENCES "province"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sub_district" ADD CONSTRAINT "FK_09117c73a9fea05a6bc03b2d160" FOREIGN KEY ("district_id") REFERENCES "district"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "village" ADD CONSTRAINT "FK_958aad05ae5c640e9fa24dc1374" FOREIGN KEY ("sub_district_id") REFERENCES "sub_district"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_category" ADD CONSTRAINT "FK_d8d3ec4a9d30bdc4605eb675349" FOREIGN KEY ("created_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_category" ADD CONSTRAINT "FK_b987f45c7218a49f447ea565fca" FOREIGN KEY ("updated_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_79e14a94835153f19f98eb9e610" FOREIGN KEY ("user_category_id") REFERENCES "user_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_2658d4029dc1bf7529ebb04c047" FOREIGN KEY ("created_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_386c59c6f0ddd6b4a28df4feaed" FOREIGN KEY ("updated_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouse" ADD CONSTRAINT "FK_7c93988bb52a8f34399d06e384b" FOREIGN KEY ("created_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouse" ADD CONSTRAINT "FK_83442811f7e6bb7209cd8d54e34" FOREIGN KEY ("updated_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "config_system" ADD CONSTRAINT "FK_b1799b0081e6b45a20521c33eb5" FOREIGN KEY ("created_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "config_system" ADD CONSTRAINT "FK_756a9cdd503fdfe1b295c71cf0f" FOREIGN KEY ("updated_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "config_system" ADD CONSTRAINT "FK_146c55651506b3967cd3e58aab2" FOREIGN KEY ("warehouse_purchase_id") REFERENCES "warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "FK_df418421464e6344efbe7e521f7" FOREIGN KEY ("created_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "FK_1a0a3dfd99afa484c4eadba78cd" FOREIGN KEY ("updated_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer" ADD CONSTRAINT "FK_2f2dfe80e19d884dd969b4c5b61" FOREIGN KEY ("village_id") REFERENCES "village"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_category" ADD CONSTRAINT "FK_02151d3744006fa1c207b9497fd" FOREIGN KEY ("created_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_category" ADD CONSTRAINT "FK_df8d4f7deb0ab03f8bcb1b87228" FOREIGN KEY ("updated_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_type" ADD CONSTRAINT "FK_6b83e867b68be9815753f36ba1c" FOREIGN KEY ("created_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_type" ADD CONSTRAINT "FK_5fb7b0c46a0179321fc258c0ba5" FOREIGN KEY ("updated_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_type" ADD CONSTRAINT "FK_edc51cf290b1a5f2ab1b9677f2f" FOREIGN KEY ("product_category_id") REFERENCES "product_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "uom" ADD CONSTRAINT "FK_1037f13dd0f437a3570cf9d1767" FOREIGN KEY ("created_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "uom" ADD CONSTRAINT "FK_80fe4c4aece20468ebda265a5e7" FOREIGN KEY ("updated_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_23adf7353b6af4637e989123f6c" FOREIGN KEY ("created_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_1f86d909884ba96239067d59953" FOREIGN KEY ("updated_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_9c47355777d0ea7c76aa31059cd" FOREIGN KEY ("product_type_id") REFERENCES "product_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_5e835b2187693a40969ab72cb73" FOREIGN KEY ("unit_retail_id") REFERENCES "uom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_6dedba093b57454ed970e170158" FOREIGN KEY ("unit_pack_id") REFERENCES "uom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_d2bdbee881d3969501fd7ded048" FOREIGN KEY ("unit_buy_id") REFERENCES "uom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier" ADD CONSTRAINT "FK_12c10d4f3c2d28843d6061f0a44" FOREIGN KEY ("created_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier" ADD CONSTRAINT "FK_02b1c335325d9c559b4106f7cfd" FOREIGN KEY ("updated_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase" ADD CONSTRAINT "FK_38cc3a0ec7fd023864c35a22c7b" FOREIGN KEY ("created_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase" ADD CONSTRAINT "FK_629bb10cc765ca5e43eb1036faa" FOREIGN KEY ("updated_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase" ADD CONSTRAINT "FK_8d9a856657c46725d085c73e4fc" FOREIGN KEY ("supplier_id") REFERENCES "supplier"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_detail" ADD CONSTRAINT "FK_ce1ae5c6119807f043e138e6c71" FOREIGN KEY ("purchase_head_id") REFERENCES "purchase"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_detail" ADD CONSTRAINT "FK_4c0d5cb87dca1bc0bd0267e1d80" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_detail" ADD CONSTRAINT "FK_ddfedcc5bef04ab876c7234d9ee" FOREIGN KEY ("unit_buy_id") REFERENCES "uom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_detail" ADD CONSTRAINT "FK_f14006cf396bf5ed49932e45514" FOREIGN KEY ("unit_retail_id") REFERENCES "uom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale" ADD CONSTRAINT "FK_78e68df2dae930ff4eb4d4a9e9a" FOREIGN KEY ("created_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale" ADD CONSTRAINT "FK_e45ee07f8b91822c3e70ba25c07" FOREIGN KEY ("updated_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale" ADD CONSTRAINT "FK_89809b48d46cc3eae0565c016e4" FOREIGN KEY ("customer_id") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_detail" ADD CONSTRAINT "FK_17d4405d0424d5c4702c22ca01f" FOREIGN KEY ("sale_head_id") REFERENCES "sale"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_detail" ADD CONSTRAINT "FK_6f193a6e12bed09dc343ad057ab" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_detail" ADD CONSTRAINT "FK_fbbef102c6c62494803d9c188c0" FOREIGN KEY ("unit_retail_id") REFERENCES "uom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_detail" ADD CONSTRAINT "FK_229623f2e60153c6c10a4e95f77" FOREIGN KEY ("unit_pack_id") REFERENCES "uom"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_card" ADD CONSTRAINT "FK_564c1c0127f0ec471a2629742b6" FOREIGN KEY ("created_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_card" ADD CONSTRAINT "FK_e19cc3126fa0c5d586c4642fc3a" FOREIGN KEY ("updated_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_card" ADD CONSTRAINT "FK_388b09c0d7dcffd6db227aa4141" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_card" ADD CONSTRAINT "FK_47604b9bc673ff69596898d686f" FOREIGN KEY ("warehouse_id") REFERENCES "warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_fifo" ADD CONSTRAINT "FK_50d9ef9f18bd03d80ea66f593b9" FOREIGN KEY ("created_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_fifo" ADD CONSTRAINT "FK_07642a66c7ae290465cc42fdbe6" FOREIGN KEY ("updated_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_fifo" ADD CONSTRAINT "FK_5c2bf02be334fb15d9d4f61b969" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock" ADD CONSTRAINT "FK_375ba760c8cff338fc8c94b416c" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock" ADD CONSTRAINT "FK_b2be25bd3e78455fe801c45e892" FOREIGN KEY ("warehouse_id") REFERENCES "warehouse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "stock" DROP CONSTRAINT "FK_b2be25bd3e78455fe801c45e892"`);
        await queryRunner.query(`ALTER TABLE "stock" DROP CONSTRAINT "FK_375ba760c8cff338fc8c94b416c"`);
        await queryRunner.query(`ALTER TABLE "stock_fifo" DROP CONSTRAINT "FK_5c2bf02be334fb15d9d4f61b969"`);
        await queryRunner.query(`ALTER TABLE "stock_fifo" DROP CONSTRAINT "FK_07642a66c7ae290465cc42fdbe6"`);
        await queryRunner.query(`ALTER TABLE "stock_fifo" DROP CONSTRAINT "FK_50d9ef9f18bd03d80ea66f593b9"`);
        await queryRunner.query(`ALTER TABLE "stock_card" DROP CONSTRAINT "FK_47604b9bc673ff69596898d686f"`);
        await queryRunner.query(`ALTER TABLE "stock_card" DROP CONSTRAINT "FK_388b09c0d7dcffd6db227aa4141"`);
        await queryRunner.query(`ALTER TABLE "stock_card" DROP CONSTRAINT "FK_e19cc3126fa0c5d586c4642fc3a"`);
        await queryRunner.query(`ALTER TABLE "stock_card" DROP CONSTRAINT "FK_564c1c0127f0ec471a2629742b6"`);
        await queryRunner.query(`ALTER TABLE "sale_detail" DROP CONSTRAINT "FK_229623f2e60153c6c10a4e95f77"`);
        await queryRunner.query(`ALTER TABLE "sale_detail" DROP CONSTRAINT "FK_fbbef102c6c62494803d9c188c0"`);
        await queryRunner.query(`ALTER TABLE "sale_detail" DROP CONSTRAINT "FK_6f193a6e12bed09dc343ad057ab"`);
        await queryRunner.query(`ALTER TABLE "sale_detail" DROP CONSTRAINT "FK_17d4405d0424d5c4702c22ca01f"`);
        await queryRunner.query(`ALTER TABLE "sale" DROP CONSTRAINT "FK_89809b48d46cc3eae0565c016e4"`);
        await queryRunner.query(`ALTER TABLE "sale" DROP CONSTRAINT "FK_e45ee07f8b91822c3e70ba25c07"`);
        await queryRunner.query(`ALTER TABLE "sale" DROP CONSTRAINT "FK_78e68df2dae930ff4eb4d4a9e9a"`);
        await queryRunner.query(`ALTER TABLE "purchase_detail" DROP CONSTRAINT "FK_f14006cf396bf5ed49932e45514"`);
        await queryRunner.query(`ALTER TABLE "purchase_detail" DROP CONSTRAINT "FK_ddfedcc5bef04ab876c7234d9ee"`);
        await queryRunner.query(`ALTER TABLE "purchase_detail" DROP CONSTRAINT "FK_4c0d5cb87dca1bc0bd0267e1d80"`);
        await queryRunner.query(`ALTER TABLE "purchase_detail" DROP CONSTRAINT "FK_ce1ae5c6119807f043e138e6c71"`);
        await queryRunner.query(`ALTER TABLE "purchase" DROP CONSTRAINT "FK_8d9a856657c46725d085c73e4fc"`);
        await queryRunner.query(`ALTER TABLE "purchase" DROP CONSTRAINT "FK_629bb10cc765ca5e43eb1036faa"`);
        await queryRunner.query(`ALTER TABLE "purchase" DROP CONSTRAINT "FK_38cc3a0ec7fd023864c35a22c7b"`);
        await queryRunner.query(`ALTER TABLE "supplier" DROP CONSTRAINT "FK_02b1c335325d9c559b4106f7cfd"`);
        await queryRunner.query(`ALTER TABLE "supplier" DROP CONSTRAINT "FK_12c10d4f3c2d28843d6061f0a44"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_d2bdbee881d3969501fd7ded048"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_6dedba093b57454ed970e170158"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_5e835b2187693a40969ab72cb73"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_9c47355777d0ea7c76aa31059cd"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_1f86d909884ba96239067d59953"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_23adf7353b6af4637e989123f6c"`);
        await queryRunner.query(`ALTER TABLE "uom" DROP CONSTRAINT "FK_80fe4c4aece20468ebda265a5e7"`);
        await queryRunner.query(`ALTER TABLE "uom" DROP CONSTRAINT "FK_1037f13dd0f437a3570cf9d1767"`);
        await queryRunner.query(`ALTER TABLE "product_type" DROP CONSTRAINT "FK_edc51cf290b1a5f2ab1b9677f2f"`);
        await queryRunner.query(`ALTER TABLE "product_type" DROP CONSTRAINT "FK_5fb7b0c46a0179321fc258c0ba5"`);
        await queryRunner.query(`ALTER TABLE "product_type" DROP CONSTRAINT "FK_6b83e867b68be9815753f36ba1c"`);
        await queryRunner.query(`ALTER TABLE "product_category" DROP CONSTRAINT "FK_df8d4f7deb0ab03f8bcb1b87228"`);
        await queryRunner.query(`ALTER TABLE "product_category" DROP CONSTRAINT "FK_02151d3744006fa1c207b9497fd"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "FK_2f2dfe80e19d884dd969b4c5b61"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "FK_1a0a3dfd99afa484c4eadba78cd"`);
        await queryRunner.query(`ALTER TABLE "customer" DROP CONSTRAINT "FK_df418421464e6344efbe7e521f7"`);
        await queryRunner.query(`ALTER TABLE "config_system" DROP CONSTRAINT "FK_146c55651506b3967cd3e58aab2"`);
        await queryRunner.query(`ALTER TABLE "config_system" DROP CONSTRAINT "FK_756a9cdd503fdfe1b295c71cf0f"`);
        await queryRunner.query(`ALTER TABLE "config_system" DROP CONSTRAINT "FK_b1799b0081e6b45a20521c33eb5"`);
        await queryRunner.query(`ALTER TABLE "warehouse" DROP CONSTRAINT "FK_83442811f7e6bb7209cd8d54e34"`);
        await queryRunner.query(`ALTER TABLE "warehouse" DROP CONSTRAINT "FK_7c93988bb52a8f34399d06e384b"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_386c59c6f0ddd6b4a28df4feaed"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_2658d4029dc1bf7529ebb04c047"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_79e14a94835153f19f98eb9e610"`);
        await queryRunner.query(`ALTER TABLE "user_category" DROP CONSTRAINT "FK_b987f45c7218a49f447ea565fca"`);
        await queryRunner.query(`ALTER TABLE "user_category" DROP CONSTRAINT "FK_d8d3ec4a9d30bdc4605eb675349"`);
        await queryRunner.query(`ALTER TABLE "village" DROP CONSTRAINT "FK_958aad05ae5c640e9fa24dc1374"`);
        await queryRunner.query(`ALTER TABLE "sub_district" DROP CONSTRAINT "FK_09117c73a9fea05a6bc03b2d160"`);
        await queryRunner.query(`ALTER TABLE "district" DROP CONSTRAINT "FK_20bbec53bfceb008df55035d900"`);
        await queryRunner.query(`DROP TABLE "stock"`);
        await queryRunner.query(`DROP TABLE "stock_fifo"`);
        await queryRunner.query(`DROP TABLE "stock_card"`);
        await queryRunner.query(`DROP TABLE "sale_detail"`);
        await queryRunner.query(`DROP TABLE "sale"`);
        await queryRunner.query(`DROP TABLE "purchase_detail"`);
        await queryRunner.query(`DROP TABLE "purchase"`);
        await queryRunner.query(`DROP TABLE "supplier"`);
        await queryRunner.query(`DROP TABLE "product"`);
        await queryRunner.query(`DROP TABLE "uom"`);
        await queryRunner.query(`DROP TABLE "tp_product_code"`);
        await queryRunner.query(`DROP TABLE "product_type"`);
        await queryRunner.query(`DROP TABLE "product_category"`);
        await queryRunner.query(`DROP TABLE "customer"`);
        await queryRunner.query(`DROP TABLE "config_system"`);
        await queryRunner.query(`DROP TABLE "warehouse"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "user_category"`);
        await queryRunner.query(`DROP TABLE "village"`);
        await queryRunner.query(`DROP TABLE "sub_district"`);
        await queryRunner.query(`DROP TABLE "district"`);
        await queryRunner.query(`DROP TABLE "province"`);
    }

}
