name: cicd

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME_2 }}
          password: ${{ secrets.DOCKER_TOKEN_2 }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME_2 }}/beenevits-api:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: actions/checkout@v3
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github-actions-key
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ secrets.AWS_HOSTNAME }}
          SSH_USER: ${{ secrets.AWS_USERNAME }}
          SSH_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
      - name: Get list from ssh remote
        run: ssh ec2 'ls -la'
      - name: Fetch new deployment config
        run: ssh ec2 'cd ~/pos-be-deployment/ && git checkout main && git fetch --all && git reset --hard origin/main && git pull origin main'
      - name: Update service and run
        run: ssh ec2 'cd ~/pos-be-deployment/src/ && sudo docker-compose down && sudo docker-compose pull && sudo docker-compose up -d && sudo docker image prune -a -f'
